// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmoxxqisirgpdlkrjbml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtb3h4cWlzaXJncGRsa3JqYm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzkwMjksImV4cCI6MjA2NDk1NTAyOX0.89jiKop60Jw9FsrVDumyoaHdi8TLE9AyOxT14yH3QuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);